name: Deploy Angular App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
    
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i --force

      - name: Build
        run: npm run build

      - name: Push build to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist/browser
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: {sha}"
